/* @flow */

export default (moduleName: string, version: string) => `/**
 * Flowtype definitions for ${moduleName}
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v${version}
 * Repo: http://github.com/anru/ts2flow
 */

`;
